<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->title; ?><?php echo $this->siteInfo["name"];?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Fidy">

    <!-- Le styles -->
    <link href="/css/common.css" rel="stylesheet">
    <link href="/jQuery.jPlayer.2.4.0/skin/blue.monday/jplayer.blue.monday.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 100px;
        padding-bottom: 40px;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.bootcss.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <![endif]-->

    
  </head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/index" title="<?php echo $this->siteInfo["name"];?>"><?php echo $this->siteInfo["name"];?></a>
          <div class="nav-collapse collapse">
            <ul class="nav">

            </ul>
            
          </div><!--/.nav-collapse -->
        </div>
	</div>
	
  </div>
      
	
<div class="container">

		<?php echo $this->layout()->content; ?>


<hr />
	<!-- footer starts -->
	<div class="footer text-center">
		
		<span>Copyright &copy; 2013 疯狂大连话</span>

	</div>
</div> <!-- /container -->



</body>
</html>
